// Code generated by internal/generate; DO NOT EDIT.
package solution

import (
	y2021d01 "github.com/ictrobot/aoc/internal/aoc2021/day01"
	y2021d02 "github.com/ictrobot/aoc/internal/aoc2021/day02"
	y2021d03 "github.com/ictrobot/aoc/internal/aoc2021/day03"
	y2021d04 "github.com/ictrobot/aoc/internal/aoc2021/day04"
	y2021d05 "github.com/ictrobot/aoc/internal/aoc2021/day05"
	y2022d01 "github.com/ictrobot/aoc/internal/aoc2022/day01"
	y2022d02 "github.com/ictrobot/aoc/internal/aoc2022/day02"
	y2022d03 "github.com/ictrobot/aoc/internal/aoc2022/day03"
	y2022d04 "github.com/ictrobot/aoc/internal/aoc2022/day04"
	y2022d05 "github.com/ictrobot/aoc/internal/aoc2022/day05"
	y2022d06 "github.com/ictrobot/aoc/internal/aoc2022/day06"
	y2022d07 "github.com/ictrobot/aoc/internal/aoc2022/day07"
	y2022d08 "github.com/ictrobot/aoc/internal/aoc2022/day08"
	y2022d09 "github.com/ictrobot/aoc/internal/aoc2022/day09"
	y2022d10 "github.com/ictrobot/aoc/internal/aoc2022/day10"
	y2022d11 "github.com/ictrobot/aoc/internal/aoc2022/day11"
	y2022d12 "github.com/ictrobot/aoc/internal/aoc2022/day12"
	y2022d13 "github.com/ictrobot/aoc/internal/aoc2022/day13"
	y2022d14 "github.com/ictrobot/aoc/internal/aoc2022/day14"
	y2022d15 "github.com/ictrobot/aoc/internal/aoc2022/day15"
	y2022d16 "github.com/ictrobot/aoc/internal/aoc2022/day16"
	y2022d17 "github.com/ictrobot/aoc/internal/aoc2022/day17"
	y2022d18 "github.com/ictrobot/aoc/internal/aoc2022/day18"
	y2022d19 "github.com/ictrobot/aoc/internal/aoc2022/day19"
	y2022d20 "github.com/ictrobot/aoc/internal/aoc2022/day20"
	y2022d21 "github.com/ictrobot/aoc/internal/aoc2022/day21"
	y2022d22 "github.com/ictrobot/aoc/internal/aoc2022/day22"
	y2022d23 "github.com/ictrobot/aoc/internal/aoc2022/day23"
	y2022d24 "github.com/ictrobot/aoc/internal/aoc2022/day24"
	y2022d25 "github.com/ictrobot/aoc/internal/aoc2022/day25"
	y2023d01 "github.com/ictrobot/aoc/internal/aoc2023/day01"
	y2023d02 "github.com/ictrobot/aoc/internal/aoc2023/day02"
	y2023d03 "github.com/ictrobot/aoc/internal/aoc2023/day03"
	y2023d04 "github.com/ictrobot/aoc/internal/aoc2023/day04"
	y2023d05 "github.com/ictrobot/aoc/internal/aoc2023/day05"
	y2023d06 "github.com/ictrobot/aoc/internal/aoc2023/day06"
	y2023d07 "github.com/ictrobot/aoc/internal/aoc2023/day07"
	y2023d08 "github.com/ictrobot/aoc/internal/aoc2023/day08"
	y2023d09 "github.com/ictrobot/aoc/internal/aoc2023/day09"
	y2023d10 "github.com/ictrobot/aoc/internal/aoc2023/day10"
	y2023d11 "github.com/ictrobot/aoc/internal/aoc2023/day11"
	y2023d12 "github.com/ictrobot/aoc/internal/aoc2023/day12"
	y2023d13 "github.com/ictrobot/aoc/internal/aoc2023/day13"
	y2023d14 "github.com/ictrobot/aoc/internal/aoc2023/day14"
	y2023d15 "github.com/ictrobot/aoc/internal/aoc2023/day15"
	y2023d16 "github.com/ictrobot/aoc/internal/aoc2023/day16"
)

// Years returns a int slice containing years with solution
func Years() []int {
	return []int{
		2021,
		2022,
		2023,
	}
}

// Days returns a int slice containing solution for the given year with a solution
func Days(year int) []int {
	switch year {
	case 2021:
		return []int{
			1,
			2,
			3,
			4,
			5,
		}
	case 2022:
		return []int{
			1,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			11,
			12,
			13,
			14,
			15,
			16,
			17,
			18,
			19,
			20,
			21,
			22,
			23,
			24,
			25,
		}
	case 2023:
		return []int{
			1,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			11,
			12,
			13,
			14,
			15,
			16,
		}
	}
	return nil
}

// For returns an implementation of a solution for the given year & day
func For(year, day int) Solution {
	switch year {
	case 2021:
		switch day {
		case 1:
			return &y2021d01.Day01{}
		case 2:
			return &y2021d02.Day02{}
		case 3:
			return &y2021d03.Day03{}
		case 4:
			return &y2021d04.Day04{}
		case 5:
			return &y2021d05.Day05{}
		}
	case 2022:
		switch day {
		case 1:
			return &y2022d01.Day01{}
		case 2:
			return &y2022d02.Day02{}
		case 3:
			return &y2022d03.Day03{}
		case 4:
			return &y2022d04.Day04{}
		case 5:
			return &y2022d05.Day05{}
		case 6:
			return &y2022d06.Day06{}
		case 7:
			return &y2022d07.Day07{}
		case 8:
			return &y2022d08.Day08{}
		case 9:
			return &y2022d09.Day09{}
		case 10:
			return &y2022d10.Day10{}
		case 11:
			return &y2022d11.Day11{}
		case 12:
			return &y2022d12.Day12{}
		case 13:
			return &y2022d13.Day13{}
		case 14:
			return &y2022d14.Day14{}
		case 15:
			return &y2022d15.Day15{}
		case 16:
			return &y2022d16.Day16{}
		case 17:
			return &y2022d17.Day17{}
		case 18:
			return &y2022d18.Day18{}
		case 19:
			return &y2022d19.Day19{}
		case 20:
			return &y2022d20.Day20{}
		case 21:
			return &y2022d21.Day21{}
		case 22:
			return &y2022d22.Day22{}
		case 23:
			return &y2022d23.Day23{}
		case 24:
			return &y2022d24.Day24{}
		case 25:
			return &y2022d25.Day25{}
		}
	case 2023:
		switch day {
		case 1:
			return &y2023d01.Day01{}
		case 2:
			return &y2023d02.Day02{}
		case 3:
			return &y2023d03.Day03{}
		case 4:
			return &y2023d04.Day04{}
		case 5:
			return &y2023d05.Day05{}
		case 6:
			return &y2023d06.Day06{}
		case 7:
			return &y2023d07.Day07{}
		case 8:
			return &y2023d08.Day08{}
		case 9:
			return &y2023d09.Day09{}
		case 10:
			return &y2023d10.Day10{}
		case 11:
			return &y2023d11.Day11{}
		case 12:
			return &y2023d12.Day12{}
		case 13:
			return &y2023d13.Day13{}
		case 14:
			return &y2023d14.Day14{}
		case 15:
			return &y2023d15.Day15{}
		case 16:
			return &y2023d16.Day16{}
		}
	}
	return nil
}
